kind: pipeline
type: kubernetes
name: build

trigger:
  branch:
    - develop
    - master
  event:
    - push
    - tag

steps:
  - name: unit_tests
    image: golang:1.14.9-alpine3.12
    environment:
      GO111MODULE: on
      CGO_ENABLED: 0
    commands:
      - go test ./...
    when:
      event:
        - push
        - tag
      branch:
        - develop
        - master

  - name: docker_build
    image: plugins/docker:18.09
    settings:
      repo: github.com/mavenir/drone-dct
      registry: hub.docker.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
    when:
      event:
        - push
        - tag
      branch:
        - develop
        - master
